sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
cache:
  bundler: true
  directories:
    - vendor/bundle
    - $HOME/.rvm
before_install:
  - openssl aes-256-cbc -K $encrypted_9c5355402a97_key -iv $encrypted_9c5355402a97_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key $USER@$SERVER_IP_ADDRESS -p $PORT pwd
install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
  - travis_retry bundle
  - jekyll build
after_success:
  - test $TRAVIS_RUBY_VERSION = "2.6.0" &&
    git clone $REMOTE_FOR_DEPLOY repository && cp _site/* repository -R &&
    cd repository && git add --all && git commit -m "Deploy!" &&
    git push origin master
notifications:
  email: false
